package theezconverter;

public class theEzConverterUI extends javax.swing.JFrame 
{
    /**
     * Creates new form theEzConverterUI
     */
    public theEzConverterUI() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        comboxUnitFrom = new javax.swing.JComboBox<>();
        txtOutput = new javax.swing.JTextField();
        comboxUnitTo = new javax.swing.JComboBox<>();
        btnConvert = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFrom.setText("From:");

        lblTo.setText("To:");

        comboxUnitFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeter", "Meter", "Kilometer", "Inch", "Feet", "Miles", "Celsius", "Fahrenheit" }));

        comboxUnitTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeter", "Meter", "Kilometer", "Inch", "Feet", "Miles", "Celsius", "Fahrenheit" }));

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConvertActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblError)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFrom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboxUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboxUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnConvert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(lblTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConvert)
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lblFrom.getAccessibleContext().setAccessibleName("lbFrom");
        lblTo.getAccessibleContext().setAccessibleName("lbTo");
        txtInput.getAccessibleContext().setAccessibleName("txtInput");
        txtOutput.getAccessibleContext().setAccessibleName("txtOutput");
        btnConvert.getAccessibleContext().setAccessibleName("btnConvert");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConvertActionPerformed
    {//GEN-HEADEREND:event_btnConvertActionPerformed
        //Creating objects
        Input userInput = new Input();
        Output userOutput = new Output();
        Unit userUnit = new Unit();
        Conversion userConversion = new Conversion();
        
        //Reset label to print error messgae
        lblError.setText("");
        
        //To get formulas from user input Combo box
        userUnit.setUnitFrom(comboxUnitFrom.getSelectedItem().toString());
        
        //To get formulas form user output combobox and get its index
        userUnit.setUnitTo(comboxUnitTo.getSelectedItem().toString());
        userUnit.setConversionFormulas();
        
        //Check if user is trying to convert from length to temperature or either.
        if (userUnit.getConversionFormulas()==0)
        {
            lblError.setText("Length & Temperature cannot convert to each other.");
        }
        
        //User exception to handle error when user trying to enter String
        //in the input text box
        try
        {
            //Assign input to user's input
            userInput.setInput(Double.parseDouble(txtInput.getText()));
        }
        catch(Exception e)
        {
            lblError.setText("Input Error, please enter only numbers.");
        }

        //Pass user's input and conversion formulas obtained.
        userConversion.setConversion(userInput.getInput(), userUnit.getConversionFormulas());
        
        //Assign output as from the conversion result
        userOutput.setOutput(userConversion.getOutput());
        
        if (userUnit.getIndexFrom()<6 && userConversion.getOutput() < 0)
        {
            lblError.setText("Length of negative does not exist in this world.");
            txtOutput.setText("Imaginary");
        }
        else
        {   
            //Set output on output textbox
            txtOutput.setText(userOutput.toString());
        }
    }//GEN-LAST:event_btnConvertActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theEzConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theEzConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theEzConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theEzConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theEzConverterUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JComboBox<String> comboxUnitFrom;
    private javax.swing.JComboBox<String> comboxUnitTo;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}

